# Generated by Django 4.2.4 on 2025-01-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mfo", models.CharField(max_length=255)),
                ("tab_number", models.CharField(max_length=255, unique=True)),
                ("crm_id", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Blank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("photo", models.ImageField(upload_to="photos/")),
                ("payment_amount", models.FloatField(blank=True, null=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("promise_to_pay", "To'lashga vada berdi"),
                            ("lost_job", "Ishsiz ekan"),
                            ("refused_to_pay", "To'lashdan bosh tortdi"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blanks",
                        to="common.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
