# Generated by Django 4.2.4 on 2025-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="employee",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
